-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.32-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table battleships.board
CREATE TABLE IF NOT EXISTS `board` (
  `player_id` enum('P1','P2') NOT NULL,
  `ColRow` varchar(3) NOT NULL DEFAULT '',
  `shipType` enum('Carrier','Battlehsip','Destroyer','Submarine','Patrol boat') DEFAULT NULL,
  `position` enum('empty','occupied','hit') NOT NULL DEFAULT 'empty',
  PRIMARY KEY (`ColRow`,`player_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table battleships.board: ~200 rows (approximately)
INSERT INTO `board` (`player_id`, `ColRow`, `shipType`, `position`) VALUES
	('P1', '1A', NULL, 'empty'),
	('P1', '1B', NULL, 'empty'),	
	('P1', '1C', NULL, 'empty'),
	('P1', '1D', NULL, 'empty'),
	('P1', '1E', NULL, 'empty'),
	('P1', '1F', NULL, 'empty'),
	('P1', '1G', NULL, 'empty'),
	('P1', '1H', NULL, 'empty'),
	('P1', '1I', NULL, 'empty'),
	('P1', '1J', NULL, 'empty'),
	('P1', '2A', NULL, 'empty'),
	('P1', '2B', NULL, 'empty'),
	('P1', '2C', NULL, 'empty'),
	('P1', '2D', NULL, 'empty'),
	('P1', '2E', NULL, 'empty'),
	('P1', '2F', NULL, 'empty'),
	('P1', '2G', NULL, 'empty'),
	('P1', '2H', NULL, 'empty'),
	('P1', '2I', NULL, 'empty'),
	('P1', '2J', NULL, 'empty'),
	('P1', '3A', NULL, 'empty'),
	('P1', '3B', NULL, 'empty'),
	('P1', '3C', NULL, 'empty'),
	('P1', '3D', NULL, 'empty'),
	('P1', '3E', NULL, 'empty'),
	('P1', '3F', NULL, 'empty'),
	('P1', '3G', NULL, 'empty'),
	('P1', '3H', NULL, 'empty'),
	('P1', '3I', NULL, 'empty'),
	('P1', '3J', NULL, 'empty'),
	('P1', '4A', NULL, 'empty'),
	('P1', '4B', NULL, 'empty'),
	('P1', '4C', NULL, 'empty'),
	('P1', '4D', NULL, 'empty'),
	('P1', '4E', NULL, 'empty'),
	('P1', '4F', NULL, 'empty'),
	('P1', '4G', NULL, 'empty'),
	('P1', '4H', NULL, 'empty'),
	('P1', '4I', NULL, 'empty'),
	('P1', '4J', NULL, 'empty'),
	('P1', '5A', NULL, 'empty'),
	('P1', '5B', NULL, 'empty'),
	('P1', '5C', NULL, 'empty'),
	('P1', '5D', NULL, 'empty'),
	('P1', '5E', NULL, 'empty'),
	('P1', '5F', NULL, 'empty'),
	('P1', '5G', NULL, 'empty'),
	('P1', '5H', NULL, 'empty'),
	('P1', '5I', NULL, 'empty'),
	('P1', '5J', NULL, 'empty'),
	('P1', '6A', NULL, 'empty'),
	('P1', '6B', NULL, 'empty'),
	('P1', '6C', NULL, 'empty'),
	('P1', '6D', NULL, 'empty'),
	('P1', '6E', NULL, 'empty'),
	('P1', '6F', NULL, 'empty'),
	('P1', '6G', NULL, 'empty'),
	('P1', '6H', NULL, 'empty'),
	('P1', '6I', NULL, 'empty'),
	('P1', '6J', NULL, 'empty'),
	('P1', '7A', NULL, 'empty'),
	('P1', '7B', NULL, 'empty'),
	('P1', '7C', NULL, 'empty'),
	('P1', '7D', NULL, 'empty'),
	('P1', '7E', NULL, 'empty'),
	('P1', '7F', NULL, 'empty'),
	('P1', '7G', NULL, 'empty'),
	('P1', '7H', NULL, 'empty'),
	('P1', '7I', NULL, 'empty'),
	('P1', '7J', NULL, 'empty'),
	('P1', '8A', NULL, 'empty'),
	('P1', '8B', NULL, 'empty'),
	('P1', '8C', NULL, 'empty'),
	('P1', '8D', NULL, 'empty'),
	('P1', '8E', NULL, 'empty'),
	('P1', '8F', NULL, 'empty'),
	('P1', '8G', NULL, 'empty'),
	('P1', '8H', NULL, 'empty'),
	('P1', '8I', NULL, 'empty'),
	('P1', '8J', NULL, 'empty'),
	('P1', '9A', NULL, 'empty'),
	('P1', '9B', NULL, 'empty'),
	('P1', '9C', NULL, 'empty'),
	('P1', '9D', NULL, 'empty'),
	('P1', '9E', NULL, 'empty'),
	('P1', '9F', NULL, 'empty'),
	('P1', '9G', NULL, 'empty'),
	('P1', '9H', NULL, 'empty'),
	('P1', '9I', NULL, 'empty'),
	('P1', '9J', NULL, 'empty'),
	('P1', '10A', NULL, 'empty'),
	('P1', '10B', NULL, 'empty'),
	('P1', '10C', NULL, 'empty'),
	('P1', '10D', NULL, 'empty'),
	('P1', '10E', NULL, 'empty'),
	('P1', '10F', NULL, 'empty'),
	('P1', '10G', NULL, 'empty'),
	('P1', '10H', NULL, 'empty'),
	('P1', '10I', NULL, 'empty'),
	('P1', '10J', NULL, 'empty'),
	('P2', '1A', NULL, 'empty'),
	('P2', '1B', NULL, 'empty'),
	('P2', '1C', NULL, 'empty'),
	('P2', '1D', NULL, 'empty'),
	('P2', '1E', NULL, 'empty'),
	('P2', '1F', NULL, 'empty'),
	('P2', '1G', NULL, 'empty'),
	('P2', '1H', NULL, 'empty'),
	('P2', '1I', NULL, 'empty'),
	('P2', '1J', NULL, 'empty'),
	('P2', '2A', NULL, 'empty'),
	('P2', '2B', NULL, 'empty'),
	('P2', '2C', NULL, 'empty'),
	('P2', '2D', NULL, 'empty'),
	('P2', '2E', NULL, 'empty'),
	('P2', '2F', NULL, 'empty'),
	('P2', '2G', NULL, 'empty'),
	('P2', '2H', NULL, 'empty'),
	('P2', '2I', NULL, 'empty'),
	('P2', '2J', NULL, 'empty'),
	('P2', '3A', NULL, 'empty'),
	('P2', '3B', NULL, 'empty'),
	('P2', '3C', NULL, 'empty'),
	('P2', '3D', NULL, 'empty'),
	('P2', '3E', NULL, 'empty'),
	('P2', '3F', NULL, 'empty'),
	('P2', '3G', NULL, 'empty'),
	('P2', '3H', NULL, 'empty'),
	('P2', '3I', NULL, 'empty'),
	('P2', '3J', NULL, 'empty'),
	('P2', '4A', NULL, 'empty'),
	('P2', '4B', NULL, 'empty'),
	('P2', '4C', NULL, 'empty'),
	('P2', '4D', NULL, 'empty'),
	('P2', '4E', NULL, 'empty'),
	('P2', '4F', NULL, 'empty'),
	('P2', '4G', NULL, 'empty'),
	('P2', '4H', NULL, 'empty'),
	('P2', '4I', NULL, 'empty'),
	('P2', '4J', NULL, 'empty'),
	('P2', '5A', NULL, 'empty'),
	('P2', '5B', NULL, 'empty'),
	('P2', '5C', NULL, 'empty'),
	('P2', '5D', NULL, 'empty'),
	('P2', '5E', NULL, 'empty'),
	('P2', '5F', NULL, 'empty'),
	('P2', '5G', NULL, 'empty'),
	('P2', '5H', NULL, 'empty'),
	('P2', '5I', NULL, 'empty'),
	('P2', '5J', NULL, 'empty'),
	('P2', '6A', NULL, 'empty'),
	('P2', '6B', NULL, 'empty'),
	('P2', '6C', NULL, 'empty'),
	('P2', '6D', NULL, 'empty'),
	('P2', '6E', NULL, 'empty'),
	('P2', '6F', NULL, 'empty'),
	('P2', '6G', NULL, 'empty'),
	('P2', '6H', NULL, 'empty'),
	('P2', '6I', NULL, 'empty'),
	('P2', '6J', NULL, 'empty'),
	('P2', '7A', NULL, 'empty'),
	('P2', '7B', NULL, 'empty'),
	('P2', '7C', NULL, 'empty'),
	('P2', '7D', NULL, 'empty'),
	('P2', '7E', NULL, 'empty'),
	('P2', '7F', NULL, 'empty'),
	('P2', '7G', NULL, 'empty'),
	('P2', '7H', NULL, 'empty'),
	('P2', '7I', NULL, 'empty'),
	('P2', '7J', NULL, 'empty'),
	('P2', '8A', NULL, 'empty'),
	('P2', '8B', NULL, 'empty'),
	('P2', '8C', NULL, 'empty'),
	('P2', '8D', NULL, 'empty'),
	('P2', '8E', NULL, 'empty'),
	('P2', '8F', NULL, 'empty'),
	('P2', '8G', NULL, 'empty'),
	('P2', '8H', NULL, 'empty'),
	('P2', '8I', NULL, 'empty'),
	('P2', '8J', NULL, 'empty'),
	('P2', '9A', NULL, 'empty'),
	('P2', '9B', NULL, 'empty'),
	('P2', '9C', NULL, 'empty'),
	('P2', '9D', NULL, 'empty'),
	('P2', '9E', NULL, 'empty'),
	('P2', '9F', NULL, 'empty'),
	('P2', '9G', NULL, 'empty'),
	('P2', '9H', NULL, 'empty'),
	('P2', '9I', NULL, 'empty'),
	('P2', '9J', NULL, 'empty'),
	('P2', '10A', NULL, 'empty'),
	('P2', '10B', NULL, 'empty'),
	('P2', '10C', NULL, 'empty'),
	('P2', '10D', NULL, 'empty'),
	('P2', '10E', NULL, 'empty'),
	('P2', '10F', NULL, 'empty'),
	('P2', '10G', NULL, 'empty'),
	('P2', '10H', NULL, 'empty'),
	('P2', '10I', NULL, 'empty'),
	('P2', '10J', NULL, 'empty');

-- Dumping structure for table battleships.board_empty
CREATE TABLE IF NOT EXISTS `board_empty` (
  `player_id` enum('P1','P2') NOT NULL,
  `ColRow` varchar(3) NOT NULL DEFAULT '',
  `shipType` enum('Carrier','Battlehsip','Destroyer','Submarine','Patrol boat') DEFAULT NULL,
  `position` enum('empty','occupied','hit') NOT NULL DEFAULT 'empty',
  PRIMARY KEY (`ColRow`,`player_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table battleships.board_empty: ~200 rows (approximately)
INSERT INTO `board_empty` (`player_id`, `ColRow`, `shipType`, `position`) VALUES
	('P1', '1A', NULL, 'empty'),
	('P1', '1B', NULL, 'empty'),	
	('P1', '1C', NULL, 'empty'),
	('P1', '1D', NULL, 'empty'),
	('P1', '1E', NULL, 'empty'),
	('P1', '1F', NULL, 'empty'),
	('P1', '1G', NULL, 'empty'),
	('P1', '1H', NULL, 'empty'),
	('P1', '1I', NULL, 'empty'),
	('P1', '1J', NULL, 'empty'),
	('P1', '2A', NULL, 'empty'),
	('P1', '2B', NULL, 'empty'),
	('P1', '2C', NULL, 'empty'),
	('P1', '2D', NULL, 'empty'),
	('P1', '2E', NULL, 'empty'),
	('P1', '2F', NULL, 'empty'),
	('P1', '2G', NULL, 'empty'),
	('P1', '2H', NULL, 'empty'),
	('P1', '2I', NULL, 'empty'),
	('P1', '2J', NULL, 'empty'),
	('P1', '3A', NULL, 'empty'),
	('P1', '3B', NULL, 'empty'),
	('P1', '3C', NULL, 'empty'),
	('P1', '3D', NULL, 'empty'),
	('P1', '3E', NULL, 'empty'),
	('P1', '3F', NULL, 'empty'),
	('P1', '3G', NULL, 'empty'),
	('P1', '3H', NULL, 'empty'),
	('P1', '3I', NULL, 'empty'),
	('P1', '3J', NULL, 'empty'),
	('P1', '4A', NULL, 'empty'),
	('P1', '4B', NULL, 'empty'),
	('P1', '4C', NULL, 'empty'),
	('P1', '4D', NULL, 'empty'),
	('P1', '4E', NULL, 'empty'),
	('P1', '4F', NULL, 'empty'),
	('P1', '4G', NULL, 'empty'),
	('P1', '4H', NULL, 'empty'),
	('P1', '4I', NULL, 'empty'),
	('P1', '4J', NULL, 'empty'),
	('P1', '5A', NULL, 'empty'),
	('P1', '5B', NULL, 'empty'),
	('P1', '5C', NULL, 'empty'),
	('P1', '5D', NULL, 'empty'),
	('P1', '5E', NULL, 'empty'),
	('P1', '5F', NULL, 'empty'),
	('P1', '5G', NULL, 'empty'),
	('P1', '5H', NULL, 'empty'),
	('P1', '5I', NULL, 'empty'),
	('P1', '5J', NULL, 'empty'),
	('P1', '6A', NULL, 'empty'),
	('P1', '6B', NULL, 'empty'),
	('P1', '6C', NULL, 'empty'),
	('P1', '6D', NULL, 'empty'),
	('P1', '6E', NULL, 'empty'),
	('P1', '6F', NULL, 'empty'),
	('P1', '6G', NULL, 'empty'),
	('P1', '6H', NULL, 'empty'),
	('P1', '6I', NULL, 'empty'),
	('P1', '6J', NULL, 'empty'),
	('P1', '7A', NULL, 'empty'),
	('P1', '7B', NULL, 'empty'),
	('P1', '7C', NULL, 'empty'),
	('P1', '7D', NULL, 'empty'),
	('P1', '7E', NULL, 'empty'),
	('P1', '7F', NULL, 'empty'),
	('P1', '7G', NULL, 'empty'),
	('P1', '7H', NULL, 'empty'),
	('P1', '7I', NULL, 'empty'),
	('P1', '7J', NULL, 'empty'),
	('P1', '8A', NULL, 'empty'),
	('P1', '8B', NULL, 'empty'),
	('P1', '8C', NULL, 'empty'),
	('P1', '8D', NULL, 'empty'),
	('P1', '8E', NULL, 'empty'),
	('P1', '8F', NULL, 'empty'),
	('P1', '8G', NULL, 'empty'),
	('P1', '8H', NULL, 'empty'),
	('P1', '8I', NULL, 'empty'),
	('P1', '8J', NULL, 'empty'),
	('P1', '9A', NULL, 'empty'),
	('P1', '9B', NULL, 'empty'),
	('P1', '9C', NULL, 'empty'),
	('P1', '9D', NULL, 'empty'),
	('P1', '9E', NULL, 'empty'),
	('P1', '9F', NULL, 'empty'),
	('P1', '9G', NULL, 'empty'),
	('P1', '9H', NULL, 'empty'),
	('P1', '9I', NULL, 'empty'),
	('P1', '9J', NULL, 'empty'),
	('P1', '10A', NULL, 'empty'),
	('P1', '10B', NULL, 'empty'),
	('P1', '10C', NULL, 'empty'),
	('P1', '10D', NULL, 'empty'),
	('P1', '10E', NULL, 'empty'),
	('P1', '10F', NULL, 'empty'),
	('P1', '10G', NULL, 'empty'),
	('P1', '10H', NULL, 'empty'),
	('P1', '10I', NULL, 'empty'),
	('P1', '10J', NULL, 'empty'),
	('P2', '1A', NULL, 'empty'),
	('P2', '1B', NULL, 'empty'),
	('P2', '1C', NULL, 'empty'),
	('P2', '1D', NULL, 'empty'),
	('P2', '1E', NULL, 'empty'),
	('P2', '1F', NULL, 'empty'),
	('P2', '1G', NULL, 'empty'),
	('P2', '1H', NULL, 'empty'),
	('P2', '1I', NULL, 'empty'),
	('P2', '1J', NULL, 'empty'),
	('P2', '2A', NULL, 'empty'),
	('P2', '2B', NULL, 'empty'),
	('P2', '2C', NULL, 'empty'),
	('P2', '2D', NULL, 'empty'),
	('P2', '2E', NULL, 'empty'),
	('P2', '2F', NULL, 'empty'),
	('P2', '2G', NULL, 'empty'),
	('P2', '2H', NULL, 'empty'),
	('P2', '2I', NULL, 'empty'),
	('P2', '2J', NULL, 'empty'),
	('P2', '3A', NULL, 'empty'),
	('P2', '3B', NULL, 'empty'),
	('P2', '3C', NULL, 'empty'),
	('P2', '3D', NULL, 'empty'),
	('P2', '3E', NULL, 'empty'),
	('P2', '3F', NULL, 'empty'),
	('P2', '3G', NULL, 'empty'),
	('P2', '3H', NULL, 'empty'),
	('P2', '3I', NULL, 'empty'),
	('P2', '3J', NULL, 'empty'),
	('P2', '4A', NULL, 'empty'),
	('P2', '4B', NULL, 'empty'),
	('P2', '4C', NULL, 'empty'),
	('P2', '4D', NULL, 'empty'),
	('P2', '4E', NULL, 'empty'),
	('P2', '4F', NULL, 'empty'),
	('P2', '4G', NULL, 'empty'),
	('P2', '4H', NULL, 'empty'),
	('P2', '4I', NULL, 'empty'),
	('P2', '4J', NULL, 'empty'),
	('P2', '5A', NULL, 'empty'),
	('P2', '5B', NULL, 'empty'),
	('P2', '5C', NULL, 'empty'),
	('P2', '5D', NULL, 'empty'),
	('P2', '5E', NULL, 'empty'),
	('P2', '5F', NULL, 'empty'),
	('P2', '5G', NULL, 'empty'),
	('P2', '5H', NULL, 'empty'),
	('P2', '5I', NULL, 'empty'),
	('P2', '5J', NULL, 'empty'),
	('P2', '6A', NULL, 'empty'),
	('P2', '6B', NULL, 'empty'),
	('P2', '6C', NULL, 'empty'),
	('P2', '6D', NULL, 'empty'),
	('P2', '6E', NULL, 'empty'),
	('P2', '6F', NULL, 'empty'),
	('P2', '6G', NULL, 'empty'),
	('P2', '6H', NULL, 'empty'),
	('P2', '6I', NULL, 'empty'),
	('P2', '6J', NULL, 'empty'),
	('P2', '7A', NULL, 'empty'),
	('P2', '7B', NULL, 'empty'),
	('P2', '7C', NULL, 'empty'),
	('P2', '7D', NULL, 'empty'),
	('P2', '7E', NULL, 'empty'),
	('P2', '7F', NULL, 'empty'),
	('P2', '7G', NULL, 'empty'),
	('P2', '7H', NULL, 'empty'),
	('P2', '7I', NULL, 'empty'),
	('P2', '7J', NULL, 'empty'),
	('P2', '8A', NULL, 'empty'),
	('P2', '8B', NULL, 'empty'),
	('P2', '8C', NULL, 'empty'),
	('P2', '8D', NULL, 'empty'),
	('P2', '8E', NULL, 'empty'),
	('P2', '8F', NULL, 'empty'),
	('P2', '8G', NULL, 'empty'),
	('P2', '8H', NULL, 'empty'),
	('P2', '8I', NULL, 'empty'),
	('P2', '8J', NULL, 'empty'),
	('P2', '9A', NULL, 'empty'),
	('P2', '9B', NULL, 'empty'),
	('P2', '9C', NULL, 'empty'),
	('P2', '9D', NULL, 'empty'),
	('P2', '9E', NULL, 'empty'),
	('P2', '9F', NULL, 'empty'),
	('P2', '9G', NULL, 'empty'),
	('P2', '9H', NULL, 'empty'),
	('P2', '9I', NULL, 'empty'),
	('P2', '9J', NULL, 'empty'),
	('P2', '10A', NULL, 'empty'),
	('P2', '10B', NULL, 'empty'),
	('P2', '10C', NULL, 'empty'),
	('P2', '10D', NULL, 'empty'),
	('P2', '10E', NULL, 'empty'),
	('P2', '10F', NULL, 'empty'),
	('P2', '10G', NULL, 'empty'),
	('P2', '10H', NULL, 'empty'),
	('P2', '10I', NULL, 'empty'),
	('P2', '10J', NULL, 'empty');

-- Dumping structure for procedure battleships.clean_board
DELIMITER //
CREATE PROCEDURE `clean_board`()
BEGIN	
	REPLACE INTO board SELECT * FROM board_empty;
END//
DELIMITER ;

-- Dumping structure for table battleships.game_status
CREATE TABLE IF NOT EXISTS `game_status` (
  `status` enum('not active','initialized','started','ended','aborted') NOT NULL DEFAULT 'not active',
  `p_turn` enum('P1','P2') DEFAULT NULL,
  `result` enum('P1','P2','D') DEFAULT NULL,
  `last_change` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table battleships.game_status: ~0 rows (approximately)
INSERT INTO `game_status` (`status`, `p_turn`, `result`, `last_change`) VALUES
	('not active', NULL, 'P1', '2023-12-23 22:08:36');

-- Dumping structure for table battleships.players
CREATE TABLE IF NOT EXISTS `players` (
  `username` varchar(20) DEFAULT NULL,
  `player_id` enum('P1','P2') NOT NULL,
  `token` varchar(100) DEFAULT NULL,
  `last_action` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`player_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table battleships.players: ~2 rows (approximately)
INSERT INTO `players` (`username`, `player_id`, `token`, `last_action`) VALUES
	(NULL, 'P1', NULL, NULL),
	(NULL, 'P2', NULL, NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
